org: agendevc
app: agendevc
service: agendevc-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Get^"
        - "dynamodb:Scan*"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-agendevcTable-${sls:stage}

  environment:
    DYNAMODB_AGENDEVC_TABLE: ${self:service}-agendevcTable-${sls:stage}

functions:
  createPrestadorServico:
    handler: functions/prestadorServico/createPrestadorServico.createPrestadorServico
    events:
      - httpApi:
          path: /addPrestadorServico
          method: post
  getAllPrestadorServico:
    handler: functions/prestadorServico/getAllPrestadorServico.getAllPrestadorServico
    events: 
      - httpApi:
          path: /getPrestadorServicos
          method: get
  createAgendamento:
    handler: functions/agendamento/createAgendamento.createAgendamento
    events: 
      - httpApi:
          path: /addAgendamento
          method: post
  getAgendamentosById:
    handler: functions/agendamento/getAgendamentoById.getAgendamentoById
    events: 
      - httpApi:
          path: /agendamento/{id}
          method: get
  getAllAgendamentos:
    handler: functions/agendamento/getAllAgendamentos.getAllAgendamentos
    events: 
      - httpApi:
          path: /getAgendamentos
          method: get
  deleteAgendamentoById:
    handler: functions/agendamento/deleteAgendamentoById.deleteAgendamentoById
    events: 
      - httpApi:
          path: /agendamento/{id}
          method: delete

resources:
  Resources:
    AgendevcTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-agendevcTable-${sls:stage}