service: agendevc-serverless-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - dynamodb:CreateTable
    Resource: '*'

functions:
  createPrestadorServico:
    handler: functions/prestadorServico/createPrestadorServico.main
    events:
      - http:
          path: addPrestadorServico
          method: post
          cors: true
  getPrestadorServicoById:
  handler: functions/prestadorServico/getPrestadorServicoById.main
  events:
    - http:
        path: getPrestador
        method: get
        cors: true